activeEnvironment: prod

browser:
    browserInUse: chrome
    headlessMode: true
    fullscreenMode: true
    takeScreenshot: true
    webElementTimeout: 15
    webElementPooling: 10

environment:
  lab:
    envName: lab
    appUrl: http://146.59.32.4/
    title: TesterSii
  prod:
    envName: prod
    appUrl: http://146.59.32.4/
    title: TesterSii
